unisoncomputing/share-api

src/Share/Backend.hs, src/Share/Codebase/Types.hs, src/Share/Postgres/Causal/Queries.hs, src/Share/Postgres/NameLookups/Ops.hs, src/Share/Postgres/NameLookups/Types.hs, src/Share/Postgres/Orphans.hs, src/Share/Postgres/Sync/Conversions.hs, src/Share/Web/Authorization.hs, src/Share/Web/Share/Branches/Impl.hs, src/Share/Web/Share/Releases/Impl.hs, src/Share/Web/UCM/Sync/Impl.hs, src/Unison/PrettyPrintEnvDecl/Postgres.hs, src/Unison/Server/NameSearch/Postgres.hs, src/Unison/Server/Share/DefinitionSummary.hs, src/Unison/Server/Share/Docs.hs, src/Unison/Server/Share/FuzzyFind.hs, src/Unison/Server/Share/NamespaceDetails.hs, src/Unison/Server/Share/RenderDoc.hs
Bumps union to latest trunk
Replaces uses of NameSegment with NameSegment.Internal; this is a quick fix, we should come back and re-visit this later to ensure Share is doing proper escaping when pretty-printing escaped names, but this change is no worse than it was before.
=> Bump unison trunk

stack.yaml
This PR just updates the `unison` submodule to the 0.5.24 tag, and updates `stack.yaml` to match.
=> update to unison 0.5.24

src/Share/Postgres/Causal/Queries.hs, src/Share/Web/Share/Contributions/API.hs, src/Share/Web/Share/Contributions/Impl.hs, src/Share/Web/Share/Diffs/Impl.hs, src/Share/Web/Share/Diffs/Types.hs, src/Share/Web/Share/Projects/API.hs, src/Share/Web/Share/Projects/Impl.hs, src/Share/Web/Share/Projects/Types.hs, src/Unison/Server/Share/Definitions.hs, src/Unison/Server/Share/RenderDoc.hs, transcripts/share-apis/contribution-diffs/contribution-diff.json, transcripts/share-apis/contribution-diffs/create-contribution-for-diff.json, transcripts/share-apis/contribution-diffs/namespace-diff.json, transcripts/share-apis/contribution-diffs/prelude.md, transcripts/share-apis/contribution-diffs/run.zsh, transcripts/share-apis/contribution-diffs/standard-term-diff.json, transcripts/share-apis/contribution-diffs/standard-type-diff.json
A small wrapper around the existing term and type diff apis which is scoped to contributions. This will allow us to use the best common ancestor for definition diffs, solving the bug we have where the diff of a PR changes unexpected when it's merged.
Adds two new endpoints:
* `/users/<handle>/projects/<slug>/contributions/<n>/diff/terms?oldTerm=old.name&newTerm=new.name`
* `/users/<handle>/projects/<slug>/contributions/<n>/diff/terms?oldType=old.name&newType=new.name`
These behave identically to the existing definition diff endpoints except that they use the best-common-ancestor that's saved on the contribution as the diff base.
=> Contribution defn diffs

src/Share/Postgres/Search/DefinitionSearch/Queries.hs, src/Share/Web/Share/Impl.hs, transcripts/share-apis/search/complex-type-mention-search.json, transcripts/share-apis/search/create-release.json, transcripts/share-apis/search/name-search-infix.json, transcripts/share-apis/search/name-search-suffix.json, transcripts/share-apis/search/prelude.md, transcripts/share-apis/search/run.zsh, transcripts/share-apis/search/similar-type-search.json, transcripts/share-apis/search/type-var-search.json
Alter the search-names auto-completer to return **the remaining suffix of any names which contain the provided query**.
E.g. `List.ma` will return the `List.map` suffix of the name `data.List.map`
=> Switch name search to return suffixes of prefixes.

src/Share/Postgres/Search/DefinitionSearch/Queries.hs, stack.yaml, stack.yaml.lock
hasql-pool returns connections with in-progress transactions to the connection pool if a non-session exception or async exception is triggered :'(
This has recently caused share outages as one exception triggers more exceptions and the connection never gets reset.
This switches to an upstream fork which changes the defaults to drop connections which encounter exceptions, see: https://github.com/ChrisPenner/hasql-pool/pull/1
Issue for discussing how to upstream this is here: https://github.com/nikita-volkov/hasql-pool/issues/46
I tested the behaviour w/r to async and sync exceptions in a local branch, otherwise the transcripts should be sufficient.
=> Use custom fork of hasql-pool for better exception handling for Postgres Connections

sql/2024-09-04-00-00_project_slug_indexes.sql, src/Share/Postgres/Queries.hs, transcripts/share-apis/code-browse/search.json, transcripts/share-apis/projects-flow/project-search-by-prefix.json, transcripts/share-apis/projects-flow/run.zsh
Project search would weirdly not actually perform a proper prefix search on slugs, only a prefix search on stemmed ts_vector tokens, which meant `statef` wouldn't match `stateful` because `stateful` gets stemmed to `state` but `statef` isn't a prefix of `state` 🙃 
This ditches the web-search syntax since nobody uses it, and adds a simple OR with a prefix search on slug.
=> Fix project slug prefix search

share-api.cabal, share-utils/package.yaml, share-utils/share-utils.cabal, share-utils/src/Share/Utils/Aeson.hs, share-utils/src/Share/Utils/URI.hs, sql/2024-11-19-00-00_namespace_diffs.sql, src/Share/BackgroundJobs.hs, src/Share/BackgroundJobs/Diffs/ContributionDiffs.hs, src/Share/BackgroundJobs/Diffs/Queries.hs, src/Share/Metrics.hs, src/Share/NamespaceDiffs.hs, src/Share/Postgres/Contributions/Queries.hs, src/Share/Postgres/NamespaceDiffs.hs, src/Share/Postgres/Projects/Queries.hs, src/Share/Prelude.hs, src/Share/Utils/Caching.hs, src/Share/Utils/Logging.hs, src/Share/Web/Errors.hs, src/Share/Web/Share/Comments/Impl.hs, src/Share/Web/Share/Contributions/Impl.hs, src/Share/Web/Share/Contributions/MergeDetection.hs, src/Share/Web/Share/Diffs/Impl.hs, src/Share/Web/Share/Diffs/Types.hs, src/Share/Web/Share/Projects/Impl.hs, transcripts/share-apis/contribution-diffs/contribution-diff.json, transcripts/share-apis/contribution-diffs/namespace-diff.json, transcripts/share-apis/contributions/merged-contribution-diff.json, transcripts/share-apis/contributions/transitive-contribution-diff.json
This change causes Share to compute diffs for Contributions in-advance using a background queue that gets populated on relevant branch updates or contribution creations.
It then returns the full diff as part of the contribution diff endpoint, see transcripts for more info 👀 
* Adds a new background job and associated PG queue table.
* Adds a table where we store the cached diffs. The diffs are based on namespace hashes, so won't ever go stale
* Adds the output to the contribution diff endpoint.
See transcripts
=> Batched background diffs

src/Share/BackgroundJobs/SerializedEntitiesMigration/Worker.hs, src/Share/Codebase.hs, src/Share/Postgres/Causal/Queries.hs, src/Share/Postgres/Definitions/Queries.hs, src/Share/Postgres/IDs.hs, src/Share/Postgres/LooseCode/Queries.hs, src/Share/Postgres/Patches/Queries.hs, src/Share/Postgres/Sync/Queries.hs
Some special cases were resulting in missing serialized entities, specifically squashing causals (for releases);
This change ensures that you can't save an entity without also adding its serialized form.
=> Ensure Serialized Entities

share-api.cabal, sql/2025-01-31_dependencies-of-causal.sql, src/Share/Web/UCM/SyncV2/Impl.hs, src/Share/Web/UCM/SyncV2/Queries.hs, src/Share/Web/UCM/SyncV2/Types.hs
Deployment
Adds a simple causal-dependencies API for UCM to determine before a pull which hashes it actually needs.
The causal-dependencies endpoint returns a stream of causals to UCM , each tagged with whether it's part of the top-level history of the root, or whether it's a lib root.
UCM can then pick out which of these dependencies it _does_ have, then send those to the server with the pull.v2 request; where Share will cull entire subtrees based on the dependencies it knows UCM has already.
This allows us to use pull.v2 in cases where it's likely to be a small update.
I've tested this locally, I'll throw it up on staging and run it through its paces.
Luckily its' back-compatible with the previous syncv2 version, which simply doesn't do the pre-negotiation.
We may wish to recurse …
=> Naïve dependency negotiation API

share-api.cabal, sql/2025-02-10_json-cache.sql, src/Share/Utils/Caching/JSON.hs, src/Unison/Server/Share/Definitions.hs, src/Unison/Server/Share/RenderDoc.hs
Redis caching is fast, but is ephemeral, there are some things where it makes sense to keep longer-lived caches, especially since using immutable hashes means we often don't ever need to bust the cache.
This adds a generic mechanism for long-lived caches which are backed by Postgres.
* Adds a new table which stores json blobs keyed by codebase, topic, and an arbitrary cache key.
* Adds `usingJSONCache` helper for easily creating/using cached values.
Tested locally.
=> Generic JSON Caching

.github/workflows/ci.yaml, src/Share/Postgres/NameLookups/Types.hs, src/Unison/Server/Share/Definitions.hs, transcripts/share-apis/contribution-diffs/contribution-diff.json, transcripts/share-apis/contribution-diffs/namespace-diff.json, transcripts/share-apis/contribution-merge/contribution-setup.output.md, transcripts/share-apis/contribution-merge/project-setup.output.md, transcripts/share-apis/contribution-merge/pull-after-merge.output.md, transcripts/share-apis/contributions/contribution-setup.output.md, transcripts/share-apis/contributions/merge-contribution-branches.output.md, transcripts/share-apis/definition-diffs/standard-ability-diff.json, transcripts/sync-apis/pull-without-history.output.md, transcripts/sync-apis/sync.output.md, transcripts/sync-apis/write-other-user-without-permission.output.md
Share wouldn't find docs for definitions in Lib if they were linked via a hash, this fixes that.
Also, use suffixified names for self-references in types and abilities
Also, render abilities on two lines, always.
We first search for the name via the hash, then we re-scope the doc search to wherever the name was found, even if that's in a lib.
Also updates the ucm version used in CI and updates transcripts to match.
* tested locally
=> Definition rendering fixes

src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Types.hs, transcripts/run-transcripts.zsh, transcripts/share-apis/code-browse/account.json, transcripts/share-apis/code-browse/codebase-browse.json, transcripts/share-apis/code-browse/codebase-definition-by-hash-constructor.json, transcripts/share-apis/code-browse/codebase-definition-by-hash-term.json, transcripts/share-apis/code-browse/codebase-definition-by-name-encoded.json, transcripts/share-apis/code-browse/codebase-definition-by-name-should-minimally-suffix-again.json, transcripts/share-apis/code-browse/codebase-definition-by-name-should-minimally-suffix.json, transcripts/share-apis/code-browse/codebase-definition-by-name-should-not-find-names-in-other-namespaces.json, transcripts/share-apis/code-browse/codebase-definition-by-name-should-pretty-print-external-names-if-no-local-name.json, transcripts/share-apis/code-browse/codebase-definition-by-name-should-work-with-empty-perspective.json, transcripts/share-apis/code-browse/codebase-definition-by-name.json, transcripts/share-apis/code-browse/codebase-find.json, transcripts/share-apis/code-browse/codebase-namespace-by-name-root.json, transcripts/share-apis/code-browse/codebase-namespace-by-name.json, transcripts/share-apis/code-browse/run.zsh, transcripts/share-apis/code-browse/search.json, transcripts/share-apis/code-browse/user-info.json, transcripts/share-apis/projects-flow/project-search.json
In some cases, like granting a user permission to a new repo, it's safest to use a user's UserId rather than their handle, since the user Id is immutable.
To enable this, we provide the UserID in search results alongside the handle, name, and avatar.
* Adds the `userId` field to the User search result JSON
* Updates transcripts, and ports the code-browse transcripts to the new format.
See transcripts
=> Add UserID to search results

.github/workflows/ci.yaml
https://github.com/actions/runner-images/issues/11101
=> Bump to new non-deprecated ubuntu image

share-auth/share-auth.cabal, share-auth/src/Share/JWT.hs, share-auth/src/Share/JWT/Types.hs, share-auth/src/Share/OAuth/Session.hs, share-auth/src/Share/OAuth/Types.hs, src/Share/NamespaceDiffs.hs, src/Share/Postgres/NameLookups/Ops.hs, src/Share/Web/Authentication/AccessToken.hs, src/Share/Web/Authentication/HashJWT.hs, src/Share/Web/Authentication/JWT.hs, src/Share/Web/Share/Branches/Impl.hs, src/Share/Web/Share/Diffs/Impl.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Releases/Impl.hs, src/Share/Web/UCM/Sync/HashJWT.hs, src/Unison/Server/Share/DefinitionSummary.hs, src/Unison/Server/Share/Definitions.hs, src/Unison/Server/Share/NamespaceListing.hs
The Jose library's interface for adding additional arbitrary jwt claims is pretty hard to work with IMO; and sometimes you want your JWT format to differ from your JSON format, this provides a separate class for doing it and simplifies the act of managing additional arbitrary claims.
=> Unify JWT interfaces into a single class

share-api.cabal, src/Share/Postgres/Authorization/Queries.hs, src/Share/Postgres/Users/Queries.hs, src/Share/Web/Authorization/Types.hs, src/Share/Web/Share/Branches/Types.hs, src/Share/Web/Share/Comments/API.hs, src/Share/Web/Share/Comments/Impl.hs, src/Share/Web/Share/Comments/Types.hs, src/Share/Web/Share/Contributions/API.hs, src/Share/Web/Share/Contributions/Impl.hs, src/Share/Web/Share/Contributions/Types.hs, src/Share/Web/Share/DisplayInfo.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Orgs/API.hs, src/Share/Web/Share/Orgs/Impl.hs, src/Share/Web/Share/Orgs/Queries.hs, src/Share/Web/Share/Roles.hs, src/Share/Web/Share/Teams/Queries.hs, src/Share/Web/Share/Tickets/API.hs, src/Share/Web/Share/Tickets/Impl.hs, src/Share/Web/Share/Tickets/Types.hs, src/Share/Web/Share/Types.hs, transcripts/share-apis/orgs/org-get-profile.json, transcripts/share-apis/orgs/run.zsh, transcripts/share-apis/users/user-profile-update.json, transcripts/share-apis/users/user-profile.json
On the user-profile endpoint, adds a `kind` which is `user` or `org`, if `org`, includes the permissions the caller has for that user. (The permissions list is included on kind = user, but will always be empty ATM.)
```
GET /users/acme
{
"avatarUrl": "https://example.com/anvil.png",
"bio": null,
"handle": "acme",
"kind": "org",
"location": null,
"name": "ACME",
"permissions": [
"project:view",
"project:manage",
"project:contribute",
"project:maintain",
"project:delete",
"org:view",
"org:manage",
"org:admin",
"org:delete",
"org:change_owner",
"org:create_project",
"team:view",
"team:manage"
],
"pronouns": null,
"twitterHandle": null,
"website": null
}
```
=> Add type of user and permissions for that user in the user-profile endpoint

package.yaml, share-api.cabal, src/Share.hs, src/Share/BackgroundJobs/Diffs/ContributionDiffs.hs, src/Share/BackgroundJobs/Diffs/Queries.hs, src/Share/BackgroundJobs/Search/DefinitionSync.hs, src/Share/Postgres/Notifications.hs, src/Share/Postgres/Search/DefinitionSearch/Queries.hs, stack.yaml
Uses Postgres LISTEN/NOTIFY to have background-job workers detect when there's work to do immediately.
This allows us to reduce our polling intervals, and process work immediately (which is nice esp. when running local transcripts)
We still need to poll since workers can crash after receiving the notifications, or things can be forgotten, but this'll help us seem more responsive without hammering Postgres with polling.
* Adds a new module with Postgres Notification Channels
* Listen on these channels in the background job workers
* Notify on these channels when inserting new work into the job queues.
If it's NOT working then transcripts will take >10 minutes to complete, so I guess we'll see :)
=> Add notification channels so we can process jobs immediately after submission

Postgres.hs, package.yaml, share-api.cabal, src/Share/BackgroundJobs/Search/DefinitionSync.hs, src/Share/Codebase.hs, src/Share/Names/Postgres.hs, src/Share/NamespaceDiffs.hs, src/Share/NamespaceDiffs/Types.hs, src/Share/NamespaceDiffs2.hs, src/Share/Postgres/NameLookups/Ops.hs, src/Share/Postgres/NameLookups/Queries.hs, src/Share/PrettyPrintEnvDecl/Postgres.hs, src/Share/Web/Share/Diffs/Impl.hs, src/Unison/Server/Share/DefinitionSummary.hs, src/Unison/Server/Share/Definitions.hs, src/Unison/Server/Share/FuzzyFind.hs, src/Unison/Server/Share/RenderDoc.hs, stack.yaml
**Choose your PR title well:** Your pull request title is what's used to create release notes, so please make it descriptive of the change itself, which may be different from the initial motivation to make the change.
What does this change accomplish and why? i.e. How does it change the user experience?
Feel free to include "before and after" examples if appropriate. (You can copy/paste screenshots directly into this editor.)
If relevant, which Github issues does it close? (See [closing-issues-using-keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords).)
How does it accomplish it, in broad strokes? i.e. How does it change the Haskell codebase?
Include anything that you thought twice about, debated, chose arbitrarily, …
=> Server-side merge

src/Share/Postgres/Users/Queries.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Types.hs, transcripts/share-apis/search/omni-search-orgs.json, transcripts/share-apis/search/omni-search-users.json, transcripts/share-apis/search/run.zsh
Previously orgs were treated as regular users in the omnisearch, now they have an `Org` tag and include the orgId.
E.g.
```
GET /search?query=uni
[
{
"avatarUrl": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?f=y&d=retro",
"handle": "unison",
"name": "Unison Org",
"orgId": "ORG-<UUID>",
"tag": "Org",
"userId": "U-<UUID>"
},
```
See transcripts
=> Add Org Tags in User Search

docker/docker-compose.yml, src/Share/Github.hs, src/Share/Postgres/Users/Queries.hs, src/Share/Web/OAuth/Impl.hs, transcripts/run-transcripts.zsh, transcripts/share-apis/user-creation/new-user-login.json, transcripts/share-apis/user-creation/new-user-profile.json, transcripts/share-apis/user-creation/run.zsh
When running in the local deployment, going through the "login" flow will short-circuit going to github and will instead complete the auth flow using dummy github user info, which helps make testing the user creation flow a lot easier.
The only difference is that it skips redirecting through Github, and doesn't call the github APIs to get the user data and instead uses constant dummy user info.
I added a new user creation transcript to ensure we don't break the user creation flow.
@hojberg  you could optionally wire up the "Login", "Register" and "Logout" buttons in the local UI if you like :)
=> Skip Github flow on local for easier testing of user creation flows

src/Share/Postgres/Users/Queries.hs, src/Share/Web/Errors.hs, src/Share/Web/OAuth/Impl.hs
If the user requests a handle that's already taken, or their github user handle is already taken, redirect them to `/finish-signup?handle=<handle>&state=handle-taken`  to allow them to request a different one.
=> Redirect to 'finish-signup' page on handle conflict

sql/2025-02-20_authz.sql, sql/2025-05-01_org-emails.sql, sql/2025-05-01_org-updates.sql, src/Share/Postgres/Users/Queries.hs, src/Share/User.hs, src/Share/Web/Share/DisplayInfo.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Orgs/Impl.hs, src/Share/Web/Share/Orgs/Operations.hs, src/Share/Web/Share/Orgs/Queries.hs, src/Share/Web/Share/Orgs/Types.hs, src/Share/Web/Share/Types.hs, src/Share/Web/Support/Zendesk.hs, src/Share/Web/Types.hs, transcripts/share-apis/orgs/org-create-by-admin.json, transcripts/share-apis/orgs/run.zsh, transcripts/share-apis/roles/grant-project-contributor.json, transcripts/share-apis/roles/org-roles-list.json, transcripts/share-apis/roles/revoke-project-contributor.json
There are a couple annoying complications at the moment:
* Creating an org also creates a row in the user table, since that's how we track project and code ownership
* Users _must_ have an email
* It's weird to require a unique email when creating an org
Solution: Allow a null email, but only for orgs
* Remove the `NOT NULL` constraint on emails
* Add an `is_org` column to the users table
* Add a check constraint so EITHER an email is required, or the row is an org user.
=> Allow null emails on orgs.

share-api.cabal, sql/2025-05-09_track_contribution_causals.sql, sql/2025-05-12_causal_diff_queue.sql, src/Share/BackgroundJobs.hs, src/Share/BackgroundJobs/Diffs/CausalDiffs.hs, src/Share/BackgroundJobs/Diffs/ContributionDiffs.hs, src/Share/BackgroundJobs/Diffs/Queries.hs, src/Share/BackgroundJobs/Diffs/Types.hs, src/Share/BackgroundJobs/Monad.hs, src/Share/Contribution.hs, src/Share/Metrics.hs, src/Share/Postgres/Contributions/Queries.hs, src/Share/Postgres/IDs.hs, src/Share/Postgres/Notifications.hs, src/Share/Postgres/Queries.hs, src/Share/Web/Share/Contributions/Impl.hs, src/Share/Web/Share/Contributions/MergeDetection.hs, src/Share/Web/UCM/Projects/Impl.hs, src/Share/Web/UCM/Sync/Impl.hs, src/Share/Web/UCM/SyncV2/Queries.hs, transcripts/share-apis/contribution-merge/contribution-after-merge.json, transcripts/share-apis/contributions/merged-contribution-diff.json, transcripts/share-apis/contributions/merged-contribution.json, transcripts/share-apis/contributions/run.zsh, transcripts/sql/clean.sql, transcripts/sql/inserts.sql
Now that contribution diffs depend on the target causal and not just the BCA we need to track that on the contribution itself so we can freeze it once merged.
* Store the current `source_causal_id` and `target_causal_id` on the contribution itself and update them when necessary
Use these causals when computing diffs rather than the _current_ state of the referenced branches.
* Carefully avoid updating these columns on contributions when the contribution is merged or is in the process of being merged.
* Replace `contribution_diff_queue` with a generic `causal_diff_queue` so we ensure no diff calculations get accidentally rolled together, and also so we can use it for generic namespace diffs
=> Store source/target causals on contribution itself, so they stay frozen once merged

src/Share/Metrics.hs, src/Share/Postgres/Metrics/Queries.hs
* Adds a new gauge for the current diff queue size
* Changes slow-metric refresh interval to 5 mins from 10 mins
=> Add metric tracking causal diff queue size

share-utils/src/Share/Debug.hs, src/Share/Postgres/NameLookups/Ops.hs, src/Share/Postgres/NameLookups/Queries.hs, src/Unison/Server/Share/FuzzyFind.hs, transcripts/share-apis/branch-browse/branch-find.json, transcripts/share-apis/code-browse/codebase-find.json
Paul was getting some weird search results within the project:
This PR improves matching based on the final search segment a bit. It's still not as good as the main term search, ideally we'll switch over project search to use that mechanism but that's a more time intensive ordeal, so this is just a short-term patch for now.
* Fix a bug in the infix-pattern matcher so the LIKE queries work as expected
* use the entire last segment of a dot-separated search when doing exact matching on last segment
* Return the name that matched in the results rather than the 'best name'
Transcripts and local testing.
=> Some basic fixups for search

app/Env.hs, share-auth/example/src/Lib.hs, share-auth/src/Share/JWT.hs, share-auth/src/Share/JWT/Types.hs
cloud-api is issuing its own tokens now, but still needs to validate Share tokens, so we must allow validating multiple issuers.
Accept a set of issuers rather than a single one.
We should test this on staging in cloud-api; but it should be strictly more lax.
Need to pull this into cloud-api
=> Update auth lib to allow multiple issuers

sql/2025-05-23_commercial-org-premium-projects.sql
Currently some features require a "premium" project, 
which currently is any project that's _either_ public or owned by an active cloud subscriber.
This change also includes projects owned by a commercial org (and since all non-commercial org projects are public, those are already covered).
Add commercial org projects to the underlying `premium_projects` view.
=> Include projects owned by a commercial org as "premium" projects

sql/2025-05-27_project-access.sql, src/Share/Postgres/Causal/Queries.hs, src/Share/Postgres/Contributions/Queries.hs, src/Share/Postgres/Queries.hs, src/Share/Postgres/Search/DefinitionSearch/Queries.hs, src/Share/Postgres/Tickets/Queries.hs, transcripts/share-apis/project-maintainers/read-maintainer-project-list-after.json, transcripts/share-apis/project-maintainers/read-maintainer-project-list-before.json, transcripts/share-apis/project-maintainers/read-maintainer-project-search-after.json, transcripts/share-apis/project-maintainers/read-maintainer-project-search-before.json, transcripts/share-apis/project-maintainers/run.zsh
A bunch of old project permissions checks only knew about whether a project was public, owned by the caller, or part of an org, they didn't respect project-maintainer roles.
This updates all the relevant queries to use the new permissions system.
Affects:
* Causal importing
* Project Search
* Projects list
* Defn Search
* Contribution listing
* Ticket listing
* Branch listing
* Adds a `user_has_project_permission` SQL function
* Wires this into all queries in-place of the old `accessible_private_projects` view
Include anything that you thought twice about, debated, chose arbitrarily, etc. 
What could have been done differently, but wasn't? And why?
=> Update all old project permissions filters

src/Share/Notifications/Queries.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Types.hs, transcripts/share-apis/code-browse/account.json, transcripts/share-apis/user-creation/new-user-profile.json
Expose whether the user has any unread notifications on the /account endpoint so Simon can show an indicator
includes `hasUnreadNotifications` field to `/account`
See transcripts
=> Add hasUnreadNotifications to /account

sql/2025-06-04_watch-projects.sql, src/Share/Notifications/Queries.hs, src/Share/Postgres/Ops.hs, src/Share/Web/Authorization.hs, src/Share/Web/Authorization/Types.hs, src/Share/Web/Share/Projects/API.hs, src/Share/Web/Share/Projects/Impl.hs, src/Share/Web/Share/Projects/Types.hs, src/Share/Web/UCM/Projects/Impl.hs, transcripts/share-apis/notifications/list-subscriptions-test-after-unsubscribe.json, transcripts/share-apis/notifications/list-subscriptions-test.json, transcripts/share-apis/notifications/run.zsh, transcripts/share-apis/notifications/unsubscribe-from-project.json, transcripts/share-apis/project-maintainers/read-maintainer-project-view.json, transcripts/share-apis/projects-flow/project-get-after-update.json, transcripts/share-apis/projects-flow/project-get-private-authorized.json, transcripts/share-apis/projects-flow/project-get-public-unauthenticated.json, transcripts/share-apis/projects-flow/project-get-simple.json, transcripts/share-apis/releases/project-latest-release.json, transcripts/share-apis/roles/maintainer-project-view.json
Adds endpoints to allow users to watch or unwatch a given project.
Adds `isSubscribed` to the GetProject response.
Auto-subscribe to projects that a given user creates.
TODO:
Adds:
```
PUT /users/<handle>/projects/<slug>/subscription
{ "isSubscribed": <bool>
}
Response:
{ "subscriptionId": NS-<UUID> | null
}
```
Adds `isSubscribed` to the Get Project response.
Transcripts
=> Add endpoints for subscribing to a project

src/Share/BackgroundJobs/Webhooks/Worker.hs, src/Share/Contribution.hs, src/Share/Notifications/Queries.hs, src/Share/Notifications/Types.hs, src/Share/Postgres/Contributions/Ops.hs, src/Share/Postgres/Contributions/Queries.hs, src/Share/Postgres/Tickets/Ops.hs, src/Share/Postgres/Tickets/Queries.hs, src/Share/Ticket.hs, src/Share/Web/Share/Contributions/Impl.hs, src/Share/Web/Share/Contributions/MergeDetection.hs, src/Share/Web/Share/Tickets/Impl.hs, src/Share/Web/UI/Links.hs, transcripts/share-apis/notifications/contribution-update-status.json, transcripts/share-apis/notifications/create-subscription-for-other-user-project.json, transcripts/share-apis/notifications/list-notifications-test.json, transcripts/share-apis/notifications/list-notifications-transcripts.json, transcripts/share-apis/notifications/list-notifications-unread-test.json, transcripts/share-apis/notifications/run.zsh, transcripts/share-apis/notifications/webhook_results.txt
Adds triggers for contribution & ticket status update notifications
* Creates notification update events when a ticket is closed or re-opened
* Creates contribution update events when a contribution is merged, closed, re-opened,  moved from draft to ready or ready to draft.
=> Status update notifications

src/Share/Notifications/Impl.hs, src/Share/Notifications/Queries.hs, src/Share/Utils/API.hs, transcripts/share-apis/notifications/list-notifications-read-transcripts.json, transcripts/share-apis/notifications/list-notifications-test-paging.json, transcripts/share-apis/notifications/list-notifications-test.json, transcripts/share-apis/notifications/list-notifications-transcripts.json, transcripts/share-apis/notifications/list-notifications-unread-test.json, transcripts/share-apis/notifications/run.zsh
Simply nulls out the nextCursor/prevCursor when there are no further results in that direction.
=> Null out paging cursors when appropriate

src/Share/Postgres/Queries.hs, transcripts/share-apis/search/omni-search-orgs.json
Previously you could only search for a single word, which isn't intuitive and also really limited its use within MCP Agent tools.
Now it uses websearch syntax, so you can do `database postgres -mysql "pipelined client"`, etc.
=> Use 'websearch' text search for projects

sql/2025-06-16_pull-speedup.sql, src/Share/Web/UCM/SyncV2/Queries.hs
Not sure this'll help, but it won't hurt.
Run migration first, then deploy.
=> Label dependency types to hopefully speed up pull

src/Share/Web/Share/Branches/Impl.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Releases/Impl.hs, src/Share/Web/Share/Types.hs, transcripts/share-apis/projects-flow/prelude.md, transcripts/share-apis/projects-flow/project-readme.json, transcripts/share-apis/projects-flow/run.zsh
Adds Markdown Readmes to the /readme endpoint in projects. this is more human readable (and AI Agent readable) than the structured readme, at very little extra cost. I'll use this in creating the Unison Share MCP tools
=> Include Markdown Readmes

src/Share/App.hs, src/Share/BackgroundJobs/Monad.hs, src/Share/ChatApps.hs, src/Share/Codebase.hs, src/Share/Env.hs, src/Share/Metrics.hs, src/Share/Postgres.hs, src/Share/Postgres/Notifications.hs, src/Share/Utils/Logging.hs, src/Share/Web/App.hs, src/Share/Web/Errors.hs, src/Share/Web/UCM/Sync/Impl.hs
Rewrites logging instances to allow us to log within transactions.
If a transaction is retried, it will re-log, but the duplicate logs will be tagged indicating as such.
=> Add logging within Transactions

src/Share/Names/Postgres.hs, src/Share/Postgres.hs, src/Share/Postgres/Hashes/Queries.hs, src/Share/Postgres/NameLookups/Conversions.hs, src/Share/Postgres/NameLookups/Ops.hs, src/Share/Postgres/NameLookups/Queries.hs, src/Share/PrettyPrintEnvDecl/Postgres.hs, src/Unison/Server/NameSearch/Postgres.hs
Previously we'd auto-insert component hash Ids for any unknown component references.
This meant that if we were ever passed references we didn't know about, we'd still store an ID for it. It's helpful during sync, but we shouldn't be doing it everywhere. It also meant we had INSERTs on read-only GET endpoints, which means a bunch of unnecessary locking on PG's part.
This changes things so we don't have these inserts on read transactions, but also makes it so we need to explicitly handle missing component hashes if/when they come up, which is much safer.
This change also makes it so that pretty-printing of decls will omit references to any record field accessors that aren't named, which was causing hiccups on prod.
* Change the `ensureComponentHashIdsOf` usages into `componentHashIdsOf` …
=> Don't always auto-insert component hashes on lookup

sql/2025-07-14_batch_name_lookups.sql, src/Share/Names/Postgres.hs, src/Share/Postgres/Definitions/Queries.hs, src/Share/Postgres/NameLookups/Ops.hs, src/Share/Postgres/NameLookups/Queries.hs, src/Share/Postgres/NameLookups/Types.hs, src/Share/PrettyPrintEnvDecl/Postgres.hs, src/Unison/Server/NameSearch/Postgres.hs
On main right now, when building pretty-printers we do at least 2 queries for EACH reference we need a name for :| 
This reduces that to 1 query to resolve ALL references and one for ALL referents; so what may have previously taken 400 queries will now take 2.
I benchmarked locally with [this diff](https://share.unison-lang.org/@unison/cloud/contributions/61/changes) from cloud.
On my laptop it went from: 490,000 queries, 14 mins
to: 260,576 queries, 7.5 mins
Since I'm chopping down the number of queries, the actual time saved is proportional to the postgres query latency, which is negligible on my laptop, so if anything I'd expect a greater savings factor on prod.
Still a lot of queries to go, but this is definitely moving the right direction :)
* Adds new batch base-level queries using …
=> Batch up name lookup queries

app/Env.hs, docker/docker-compose.yml, docker/otel-collector-config.yaml, local.env, package.yaml, share-api.cabal, src/Share.hs, src/Share/App.hs, src/Share/BackgroundJobs/Diffs/CausalDiffs.hs, src/Share/BackgroundJobs/Monad.hs, src/Share/BackgroundJobs/Search/DefinitionSync.hs, src/Share/BackgroundJobs/Webhooks/Worker.hs, src/Share/ChatApps.hs, src/Share/Env.hs, src/Share/Metrics.hs, src/Share/NamespaceDiffs.hs, src/Share/Postgres.hs, src/Share/Telemetry.hs, src/Share/Telemetry/Setup.hs, src/Share/Utils/Logging.hs, src/Share/Utils/Tags.hs, src/Share/Web/App.hs, src/Share/Web/Authorization.hs, src/Share/Web/Errors.hs, src/Share/Web/Share/Diffs/Impl.hs, src/Share/Web/UCM/Projects/Impl.hs, src/Share/Web/UCM/Sync/Impl.hs, stack.yaml, stack.yaml.lock
Adds open telemetry instrumentation for better observability.
Currently we don't actually collect these on prod, but that should be relatively easy to set up.
* Adds open telemetry middleware to tag every request with a span
* Adds a new `withSpan` helper for spans in App code
* Adds `transactionSpan` for adding a span to a chunk of code in a transaction
* Auto-tags every transaction with its callsite.
* Tracks the number of queries made within each transaction.
* Allows enabling a span for every query, but this is disabled by default cuz it's too noisy and would likely slow the app down.
=> Add Open Telemetry

src/Share/Names/Postgres.hs, src/Share/Postgres.hs, src/Share/Postgres/Causal/Queries.hs, src/Share/Prelude/Orphans.hs, src/Share/PrettyPrintEnvDecl/Postgres.hs, src/Share/Utils/Tags.hs
Adds spans in large batch operations like building pretty printers, names objects, etc.
Embeds `MonadTracer` and `MonadTags` in QueryM for convenience.
=> Track a few additional spans for observability

share-api.cabal, src/Share/Backend.hs, src/Share/BackgroundJobs/Diffs/CausalDiffs.hs, src/Share/BackgroundJobs/Search/DefinitionSync.hs, src/Share/Codebase.hs, src/Share/Codebase/CodeCache.hs, src/Share/Codebase/CodebaseRuntime.hs, src/Share/Codebase/Types.hs, src/Share/Postgres.hs, src/Share/Postgres/Definitions/Queries.hs, src/Share/Prelude/Orphans.hs, src/Share/Utils/Tags.hs, src/Share/Web/Share/Branches/Impl.hs, src/Share/Web/Share/Contributions/Impl.hs, src/Share/Web/Share/Impl.hs, src/Share/Web/Share/Projects/Impl.hs, src/Share/Web/Share/Releases/Impl.hs, src/Unison/Server/Share/Definitions.hs
Doc evaluation is getting pretty slow; the current trunk implementation will evaluate a little, then the runtime will ask for more dependencies, it'll call out to Postgres to load a single dependency, then more eval, then another single definition, etc. It's extremely inefficient to do it this way.
Instead, it now crawls the doc's transitive dependencies and pre-loads them all into a code cache. The runtime still asks for them one at a time, but now they'll be provided from an in-memory map rather than making a DB call 😎 
On local I'm getting about a 10x speedup on one particularly beefy doc, this will be larger on production where DB calls are more costly.
* The "CodeLookup" interface is too specialized to UCM to be useful anymore, so I added a new CodeCache concept, then allow …
=> Speed up doc evaluation on Share

.gitignore, Makefile, README.md, transcripts/fixtures/load-from-share.sh, transcripts/fixtures/projects.txt, transcripts/fixtures/run.zsh
Now `make reset_fixtures` will copy the projects from `transcripts/fixtures/projects.txt` and `transcripts/fixtures/custom_projects.txt` into your local dv server from prod.
You can customize `transcripts/fixtures/custom_projects.txt` to your needs, it's gitignore'd
Generates the needed ucm transcripts from the listed projects, then runs a UCM against prod to clone, and a transcript against local to push.
lots of bash... 😬
=> Copy select projects from prod in `reset_fixtures`

src/Share/Postgres/Queries.hs, src/Share/Web/Share/Branches/Impl.hs, transcripts/share-apis/branches/branch-list-by-self-name-prefix.json, transcripts/share-apis/branches/branch-list-by-self-project-ref.json, transcripts/share-apis/branches/branch-list-contributor-filter.json, transcripts/share-apis/branches/branch-list-contributor-prefix.json, transcripts/share-apis/branches/branch-list-contributors-only.json, transcripts/share-apis/branches/branch-list-name-filter.json, transcripts/share-apis/branches/branch-list-name-prefix.json, transcripts/share-apis/branches/branch-list-page-1.json, transcripts/share-apis/branches/branch-list-page-2.json, transcripts/share-apis/branches/branch-list-prev-page.json, transcripts/share-apis/branches/branch-list-private.json, transcripts/share-apis/branches/branch-list.json, transcripts/share-apis/branches/run.zsh
Make the branch paging APIs behave like the notifications hub ones.
Fixes the paging on the branch list APIs, they were buggy before.
Added some paging transcripts
=> Fix branch paging

src/Share/Web/Admin/API.hs, src/Share/Web/Admin/Impl.hs, src/Share/Web/Admin/Types.hs
Allow admins to create orgs via API so I don't have to be carefully copy paste SQL to do it.
Adds an admin-only endpoint for creating privileged orgs
Tested locally
=> Add admin endpoint for creating orgs

src/Share/Utils/Unison.hs
Removes unused dependencies on old Unison backend stuff.
=> Remove dependencies on old unison Backend utils
